[[pages]]
name = "File Submission"
# icon = "ğŸˆï¸"
is_section = true

[[pages]]
path = "Hello.py"
name = "File Submission Form"
# icon = "ğŸ "

[[pages]]
name = "Review Files"
# icon = "ğŸˆï¸"
is_section = true

[[pages]]
path = "pg01_Mamm"
name = "Mamm Files"
# icon = "ğŸ’ª"

[[pages]]
path = "pg02_CIS"
name = "CIS Files"
# icon = "ğŸ’ª"

[[pages]]
path = "pg03_Vein"
name = "Vein Files"
# icon = "ğŸ’ª"