[[pages]]
name = "File Submission"
icon = "ğŸ "
is_section = true

[[pages]]
path = "Hello.py"
name = "File Submission Form"
icon = "ğŸ“"

[[pages]]
name = "Review Files"
icon = "ğŸ—ƒ"
is_section = true

[[pages]]
path = "pg01_Mamm.py"
name = "Mamm Files"
icon = "ğŸ¥"

[[pages]]
path = "pg02_CIS.py"
name = "CIS Files"
icon = "ğŸ¥"

[[pages]]
path = "pg03_Vein.py"
name = "Vein Files"
icon = "ğŸ¥"